# Generated by Django 6.0.7 on 2026-07-31 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('titular', models.CharField(max_length=200)),
                ('documento', models.CharField(blank=True, max_length=20)),
                ('tipo', models.CharField(choices=[('e-CPF', 'e-CPF'), ('e-CNPJ', 'e-CNPJ'), ('NF-e', 'NF-e'), ('SSL', 'SSL'), ('Outro', 'Outro')], default='e-CPF', max_length=10)),
                ('modelo', models.CharField(choices=[('A1', 'A1'), ('A3', 'A3')], default='A1', max_length=2)),
                ('emissao', models.DateField(blank=True, null=True)),
                ('vencimento', models.DateField()),
                ('emissora', models.CharField(blank=True, max_length=100)),
                ('local', models.CharField(blank=True, max_length=200)),
                ('responsavel', models.CharField(blank=True, max_length=100)),
                ('obs', models.TextField(blank=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['vencimento'],
                'indexes': [models.Index(fields=['tipo', 'vencimento'], name='certs_certi_tipo_ce2444_idx'), models.Index(fields=['deleted_at'], name='certs_certi_deleted_885c3a_idx')],
            },
        ),
    ]
